name: Node.js CI
env:
  BUILD_TARGET: DEFAULT
on:
  push:
    branches: [master]
    paths:
      - 'cities/**/*'
      - 'js/**/*'
      - 'lib/**/*'
      - 'preprocessing/**/*'
      - 'spec/**/*'
      - 'validation/**/*'
      - '.github/workflows/**/*'
      - 'package*.json'
  pull_request:
    branches: [master, staging, demo, dev]
    paths:
      - 'cities/**/*'
      - 'js/**/*'
      - 'lib/**/*'
      - 'preprocessing/**/*'
      - 'spec/**/*'
      - 'validation/**/*'
      - '.github/workflows/**/*'
      - 'package*.json'
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
      - 'ready_for_review'
      - 'edited'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test